---
name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
    workflow_dispatch:
        inputs:
            # FIXME: Not yet implemented
            conan_id:
                required: false
                type: string
                description: 'The full conan package ID, e.g. "libnest2d/1.2.3@ultimaker/stable"'
            create_latest_alias:
                required: true
                default: false
                type: boolean
                description: 'Create latest alias'
            create_binaries_windows:
                required: true
                default: false
                type: boolean
                description: 'create binaries Windows'
            create_binaries_linux:
                required: true
                default: false
                type: boolean
                description: 'create binaries Linux'
            create_binaries_macos:
                required: true
                default: false
                type: boolean
                description: 'create binaries Macos'

    push:
        paths:
            - 'python/**'
            - 'test_package/**'
            - 'cmake/**'
            - 'conanfile.py'
            - 'conandata.yml'
            - 'CMakeLists.txt'
            - '.github/workflows/conan-package.yml'
            - '.github/workflows/requirements*'
        branches:
            - main
            - 'CURA-*'
            - '[0-9]+.[0-9]+'
        tags:
            - '[0-9]+.[0-9]+.[0-9]*'

jobs:
    conan-package-create-windows:
        if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master' || needs.conan-recipe-version.outputs.is_release_branch)) || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_windows) }}
        
        uses: ultimaker/cura/.github/workflows/conan-package-create.yml@main
        with:
            project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            build_id: 4
            build_info: false
            runs_on: 'windows-2022'
            python_version: '3.11.x'
            conan_config_branch: ''
            conan_logging_level: 'info'
        secrets: inherit




